"""a

Revision ID: 823c0289beda
Revises: 
Create Date: 2023-03-16 09:43:40.302822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823c0289beda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snkr', sa.Integer(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sneaker', ['snkr'], ['id'])
        batch_op.drop_column('sneaker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sneaker', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sneaker', ['sneaker'], ['id'])
        batch_op.alter_column('size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('snkr')

    # ### end Alembic commands ###
