"""a

Revision ID: dd96c164535e
Revises: 
Create Date: 2023-03-16 13:16:01.706123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd96c164535e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
